### ISSUE TITLE
removed from pip

### ISSUE THREAD

**Issue by hamaney** [andrewp-as-is/launchagents.py#1]
`pip install launchagents`  is not working anymore. a week ago it was working.

**Comment by looking-for-a-job** [comment]
bad concept, removed. 
i did another packages: 
launchd-generator https://github.com/looking-for-a-job/launchd-generator
launchd-env https://github.com/looking-for-a-job/launchd-env.py
launchd-logs https://github.com/looking-for-a-job/launchd-logs.py

**Comment by hamaney** [comment]
I like how things are broken down now but I cannot see `load()`, `unload()`, and  `find()`

**Comment by looking-for-a-job** [comment]
I thought this functionality is not needed by anyone))
ok, i restored the package

**Comment by hamaney** [comment]
Dude lol ... I love this library; don't underestimate ur stuff. It is a great help for many developers 8 am sure. However I think we are just lazy and like to use code without star or fork the repo. Keep up the good work. Also add a donation button to ur repos ;)
